# Generated by Django 5.1.4 on 2024-12-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='Orders',
        ),
    ]
