# Generated by Django 5.1.4 on 2024-12-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
